name: iOS CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
      paths-ignore:
        - 'androidApp/**'
        - '.github/workflows/android**'

jobs:
  ios-ci:
    runs-on: macos-12

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Set up ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.6.6'

      - name: Generate dummy framework
        run: ./gradlew shared:generateDummyFramework --info

      - name: Run podGenIOS
        run: ./gradlew shared:podGenIOS --info

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '14.0.1'

      - name: Install Pods
        run: |
          cd iosApp/
          pod install --repo-update

      - name: Build Xcode project
        run: |
          xcodebuild \
          -workspace iosApp/iosApp.xcworkspace \
          -scheme iosApp \
          -sdk iphonesimulator16.0 \
          -destination 'platform=iOS Simulator,name=iPhone 11,OS=16.0' \
          test

      - name: Run shared X64 iOS tests
        run: ./gradlew shared:iosX64Test